##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://will321.github.io
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /virtual-exhibition
# location of code, the full url to your github repository
source-code: https://github.com/will321/virtual-exhibition.git

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "The Other" in Yuan Dynasty Painting
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a template for creating simple digital exhibits
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
About This Collection: "The reunification of the Chinese empires under Mongol rule in the Yuan dynasty (1271-1368) saw a cultural shift towards syncretism of different cultures. The arts, particularly paintings, showed evidence of the mixing and coexistence of diverse cultures, people, ideology and religion.

This exhibition showcases a selection of paintings by Han-Chinese artists that depicts the idea of the foreign and ethnic other, visually and/or figuratively. The visual evidence is obvious in the depiction of figures with different ethnicities (such as people from Central or Western Asia), clothing and religious anecdotes or symbols. The other can also be depicted metaphorically and symbolized by the supernatural, as seen in Gong Kai’s painting.

Whether or not the artists intended for these works to be pure visual depictions or to contain political and personal messages, all of these paintings function as a visual peek into society. Serving as a helpful way to better understand and describe the complexity and dynamics of the Yuan dynasty culture.
"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection)
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: exhibition-metadata

##########
# Site/Organization Branding
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id:

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true

##########
# BUILD SETTINGS
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
